### PR TITLE
Project environment initial setup

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/unfoldingword/create-app/15)

### CODE REVIEW

**Review by PhotoNomad0 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/create-app/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Review by PhotoNomad0 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/create-app/15)* status: all files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/components/BibleReference.js, line 13 at r2](https://reviewable.io/reviews/unfoldingword/create-app/15#-MQDzIm66N7IT3nBAi6X:-MQDzIm66N7IT3nBAi6Y:b-cxvu3t) ([raw file](https://github.com/unfoldingword/create-app/blob/03ec9dba1ea368872c80488b035cae6228a238e6/src/components/BibleReference.js#L13)):*
> ```JavaScript
>   } = useContext(ReferenceContext)
> 
>   const { state, actions } = useBibleReference({
> ```

Probably want to move useBibleReference() call down into the main app so that the state and actions are accessible by other modules.

**Comment by mannycolon** [comment]
Actually, I'm using the ReferenceContext to share the bible reference state and action with the entire app @PhotoNomad0

**Comment by PhotoNomad0** [comment]
@mannycolon - OK, see that now.  Maybe sometime you can explain how that works to me with the shared context. LGTM

**Review by PhotoNomad0 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/create-app/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mannycolon)

**Pull request merged**
